package com.data.mapper;

import com.data.pojo.CmsArticles;
import com.data.pojo.CmsArticlesCriteria;
import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface CmsArticlesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_articles
     *
     * @mbg.generated
     */
    int countByExample(CmsArticlesCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_articles
     *
     * @mbg.generated
     */
    int insert(CmsArticles record);

    void update(@Param("article") CmsArticles article);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_articles
     *
     * @mbg.generated
     */
    int insertSelective(CmsArticles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_articles
     *
     * @mbg.generated
     */
    List<CmsArticles> selectByExampleWithBLOBsWithRowbounds(CmsArticlesCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_articles
     *
     * @mbg.generated
     */
    List<CmsArticles> selectByExampleWithBLOBs(CmsArticlesCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_articles
     *
     * @mbg.generated
     */
    List<CmsArticles> selectByExampleWithRowbounds(CmsArticlesCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_articles
     *
     * @mbg.generated
     */
    List<CmsArticles> selectByExample(CmsArticlesCriteria example);

    /**
     * 更新文章删除状态
     * @param articleId 文章id
     * @param isDelete 是否删除，true删除，false未删除
     * @return
     */
    int updateDeleteFlag(@Param("articleId") int articleId, @Param("isDelete") boolean isDelete);
}