package com.data.mapper;

import com.data.pojo.CmsArticle;
import com.data.pojo.CmsArticleCriteria;
import java.util.List;
import org.apache.ibatis.session.RowBounds;

public interface CmsArticleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article
     *
     * @mbg.generated
     */
    long countByExample(CmsArticleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article
     *
     * @mbg.generated
     */
    int insert(CmsArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article
     *
     * @mbg.generated
     */
    int insertSelective(CmsArticle record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article
     *
     * @mbg.generated
     */
    List<CmsArticle> selectByExampleWithBLOBsWithRowbounds(CmsArticleCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article
     *
     * @mbg.generated
     */
    List<CmsArticle> selectByExampleWithBLOBs(CmsArticleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article
     *
     * @mbg.generated
     */
    List<CmsArticle> selectByExampleWithRowbounds(CmsArticleCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article
     *
     * @mbg.generated
     */
    List<CmsArticle> selectByExample(CmsArticleCriteria example);
}