package com.data.mapper;

import com.data.pojo.CmsChannel;
import com.data.pojo.CmsChannelCriteria;
import java.util.List;
import org.apache.ibatis.session.RowBounds;

public interface CmsChannelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_channel
     *
     * @mbg.generated
     */
    int insert(CmsChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_channel
     *
     * @mbg.generated
     */
    int insertSelective(CmsChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_channel
     *
     * @mbg.generated
     */
    List<CmsChannel> selectByExampleWithRowbounds(CmsChannelCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_channel
     *
     * @mbg.generated
     */
    List<CmsChannel> selectByExample(CmsChannelCriteria example);
}