package com.data.mapper;

import com.data.model.ResourceItem;
import com.data.pojo.CmsResource;
import com.data.pojo.CmsResourceCriteria;

import java.util.List;
import java.util.Set;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface CmsResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_resource
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer resourceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_resource
     *
     * @mbg.generated
     */
    int insert(CmsResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_resource
     *
     * @mbg.generated
     */
    int insertSelective(CmsResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_resource
     *
     * @mbg.generated
     */
    List<CmsResource> selectByExampleWithRowbounds(CmsResourceCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_resource
     *
     * @mbg.generated
     */
    List<CmsResource> selectByExample(CmsResourceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_resource
     *
     * @mbg.generated
     */
    CmsResource selectByPrimaryKey(Integer resourceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_resource
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CmsResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_resource
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CmsResource record);


    Set<CmsResource> findByRoleId(@Param("roleId") Integer roleId);

    List<CmsResource> findAllResources();

    List<CmsResource> findByUserId(@Param("userId") int userId);
}