package com.data.mapper;

import com.data.pojo.CmsUser;
import com.data.pojo.CmsUserCriteria;
import java.util.List;
import org.apache.ibatis.session.RowBounds;

public interface CmsUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user
     *
     * @mbg.generated
     */
    int insert(CmsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user
     *
     * @mbg.generated
     */
    int insertSelective(CmsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user
     *
     * @mbg.generated
     */
    List<CmsUser> selectByExampleWithRowbounds(CmsUserCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user
     *
     * @mbg.generated
     */
    List<CmsUser> selectByExample(CmsUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user
     *
     * @mbg.generated
     */
    CmsUser selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CmsUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CmsUser record);
}