package com.data.mapper;

import com.data.pojo.CmsUserRoleRelCriteria;
import com.data.pojo.CmsUserRoleRelKey;
import java.util.List;
import org.apache.ibatis.session.RowBounds;

public interface CmsUserRoleRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role_rel
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(CmsUserRoleRelKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role_rel
     *
     * @mbg.generated
     */
    int insert(CmsUserRoleRelKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role_rel
     *
     * @mbg.generated
     */
    int insertSelective(CmsUserRoleRelKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role_rel
     *
     * @mbg.generated
     */
    List<CmsUserRoleRelKey> selectByExampleWithRowbounds(CmsUserRoleRelCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_user_role_rel
     *
     * @mbg.generated
     */
    List<CmsUserRoleRelKey> selectByExample(CmsUserRoleRelCriteria example);
}