package com.data.pojo;

import java.io.Serializable;
import java.util.Date;

public class CmsArticle implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article.audit_flag
     *
     * @mbg.generated
     */
    private String auditFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article.create_date
     *
     * @mbg.generated
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article.delete_flag
     *
     * @mbg.generated
     */
    private String deleteFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article.update_date
     *
     * @mbg.generated
     */
    private Date updateDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article.cover_image_url
     *
     * @mbg.generated
     */
    private String coverImageUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article.href
     *
     * @mbg.generated
     */
    private String href;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article.order_no
     *
     * @mbg.generated
     */
    private Integer orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article.publisher
     *
     * @mbg.generated
     */
    private String publisher;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article.source_from
     *
     * @mbg.generated
     */
    private String sourceFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article.summary
     *
     * @mbg.generated
     */
    private String summary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article.title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article.column_info_id
     *
     * @mbg.generated
     */
    private String columnInfoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article.is_audit
     *
     * @mbg.generated
     */
    private Boolean isAudit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article.is_top
     *
     * @mbg.generated
     */
    private Boolean isTop;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article.view_count
     *
     * @mbg.generated
     */
    private Integer viewCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article.root_column_info_id
     *
     * @mbg.generated
     */
    private String rootColumnInfoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_article.content
     *
     * @mbg.generated
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cms_article
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article.id
     *
     * @return the value of cms_article.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article.id
     *
     * @param id the value for cms_article.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article.audit_flag
     *
     * @return the value of cms_article.audit_flag
     *
     * @mbg.generated
     */
    public String getAuditFlag() {
        return auditFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article.audit_flag
     *
     * @param auditFlag the value for cms_article.audit_flag
     *
     * @mbg.generated
     */
    public void setAuditFlag(String auditFlag) {
        this.auditFlag = auditFlag == null ? null : auditFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article.create_date
     *
     * @return the value of cms_article.create_date
     *
     * @mbg.generated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article.create_date
     *
     * @param createDate the value for cms_article.create_date
     *
     * @mbg.generated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article.delete_flag
     *
     * @return the value of cms_article.delete_flag
     *
     * @mbg.generated
     */
    public String getDeleteFlag() {
        return deleteFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article.delete_flag
     *
     * @param deleteFlag the value for cms_article.delete_flag
     *
     * @mbg.generated
     */
    public void setDeleteFlag(String deleteFlag) {
        this.deleteFlag = deleteFlag == null ? null : deleteFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article.update_date
     *
     * @return the value of cms_article.update_date
     *
     * @mbg.generated
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article.update_date
     *
     * @param updateDate the value for cms_article.update_date
     *
     * @mbg.generated
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article.cover_image_url
     *
     * @return the value of cms_article.cover_image_url
     *
     * @mbg.generated
     */
    public String getCoverImageUrl() {
        return coverImageUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article.cover_image_url
     *
     * @param coverImageUrl the value for cms_article.cover_image_url
     *
     * @mbg.generated
     */
    public void setCoverImageUrl(String coverImageUrl) {
        this.coverImageUrl = coverImageUrl == null ? null : coverImageUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article.href
     *
     * @return the value of cms_article.href
     *
     * @mbg.generated
     */
    public String getHref() {
        return href;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article.href
     *
     * @param href the value for cms_article.href
     *
     * @mbg.generated
     */
    public void setHref(String href) {
        this.href = href == null ? null : href.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article.order_no
     *
     * @return the value of cms_article.order_no
     *
     * @mbg.generated
     */
    public Integer getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article.order_no
     *
     * @param orderNo the value for cms_article.order_no
     *
     * @mbg.generated
     */
    public void setOrderNo(Integer orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article.publisher
     *
     * @return the value of cms_article.publisher
     *
     * @mbg.generated
     */
    public String getPublisher() {
        return publisher;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article.publisher
     *
     * @param publisher the value for cms_article.publisher
     *
     * @mbg.generated
     */
    public void setPublisher(String publisher) {
        this.publisher = publisher == null ? null : publisher.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article.source_from
     *
     * @return the value of cms_article.source_from
     *
     * @mbg.generated
     */
    public String getSourceFrom() {
        return sourceFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article.source_from
     *
     * @param sourceFrom the value for cms_article.source_from
     *
     * @mbg.generated
     */
    public void setSourceFrom(String sourceFrom) {
        this.sourceFrom = sourceFrom == null ? null : sourceFrom.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article.summary
     *
     * @return the value of cms_article.summary
     *
     * @mbg.generated
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article.summary
     *
     * @param summary the value for cms_article.summary
     *
     * @mbg.generated
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article.title
     *
     * @return the value of cms_article.title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article.title
     *
     * @param title the value for cms_article.title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article.column_info_id
     *
     * @return the value of cms_article.column_info_id
     *
     * @mbg.generated
     */
    public String getColumnInfoId() {
        return columnInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article.column_info_id
     *
     * @param columnInfoId the value for cms_article.column_info_id
     *
     * @mbg.generated
     */
    public void setColumnInfoId(String columnInfoId) {
        this.columnInfoId = columnInfoId == null ? null : columnInfoId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article.is_audit
     *
     * @return the value of cms_article.is_audit
     *
     * @mbg.generated
     */
    public Boolean getIsAudit() {
        return isAudit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article.is_audit
     *
     * @param isAudit the value for cms_article.is_audit
     *
     * @mbg.generated
     */
    public void setIsAudit(Boolean isAudit) {
        this.isAudit = isAudit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article.is_top
     *
     * @return the value of cms_article.is_top
     *
     * @mbg.generated
     */
    public Boolean getIsTop() {
        return isTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article.is_top
     *
     * @param isTop the value for cms_article.is_top
     *
     * @mbg.generated
     */
    public void setIsTop(Boolean isTop) {
        this.isTop = isTop;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article.view_count
     *
     * @return the value of cms_article.view_count
     *
     * @mbg.generated
     */
    public Integer getViewCount() {
        return viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article.view_count
     *
     * @param viewCount the value for cms_article.view_count
     *
     * @mbg.generated
     */
    public void setViewCount(Integer viewCount) {
        this.viewCount = viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article.root_column_info_id
     *
     * @return the value of cms_article.root_column_info_id
     *
     * @mbg.generated
     */
    public String getRootColumnInfoId() {
        return rootColumnInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article.root_column_info_id
     *
     * @param rootColumnInfoId the value for cms_article.root_column_info_id
     *
     * @mbg.generated
     */
    public void setRootColumnInfoId(String rootColumnInfoId) {
        this.rootColumnInfoId = rootColumnInfoId == null ? null : rootColumnInfoId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article.type
     *
     * @return the value of cms_article.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article.type
     *
     * @param type the value for cms_article.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_article.content
     *
     * @return the value of cms_article.content
     *
     * @mbg.generated
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_article.content
     *
     * @param content the value for cms_article.content
     *
     * @mbg.generated
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_article
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", auditFlag=").append(auditFlag);
        sb.append(", createDate=").append(createDate);
        sb.append(", deleteFlag=").append(deleteFlag);
        sb.append(", updateDate=").append(updateDate);
        sb.append(", coverImageUrl=").append(coverImageUrl);
        sb.append(", href=").append(href);
        sb.append(", orderNo=").append(orderNo);
        sb.append(", publisher=").append(publisher);
        sb.append(", sourceFrom=").append(sourceFrom);
        sb.append(", summary=").append(summary);
        sb.append(", title=").append(title);
        sb.append(", columnInfoId=").append(columnInfoId);
        sb.append(", isAudit=").append(isAudit);
        sb.append(", isTop=").append(isTop);
        sb.append(", viewCount=").append(viewCount);
        sb.append(", rootColumnInfoId=").append(rootColumnInfoId);
        sb.append(", type=").append(type);
        sb.append(", content=").append(content);
        sb.append("]");
        return sb.toString();
    }
}