package com.data.pojo;

import java.io.Serializable;
import java.util.Date;

public class CmsChannel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_channel.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_channel.channelName
     *
     * @mbg.generated
     */
    private String channelname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_channel.level
     *
     * @mbg.generated
     */
    private String level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_channel.parentId
     *
     * @mbg.generated
     */
    private Integer parentid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_channel.orderNum
     *
     * @mbg.generated
     */
    private Integer ordernum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_channel.icon
     *
     * @mbg.generated
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_channel.isDel
     *
     * @mbg.generated
     */
    private String isdel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_channel.createTime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_channel.updateTime
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cms_channel
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_channel.id
     *
     * @return the value of cms_channel.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_channel.id
     *
     * @param id the value for cms_channel.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_channel.channelName
     *
     * @return the value of cms_channel.channelName
     *
     * @mbg.generated
     */
    public String getChannelname() {
        return channelname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_channel.channelName
     *
     * @param channelname the value for cms_channel.channelName
     *
     * @mbg.generated
     */
    public void setChannelname(String channelname) {
        this.channelname = channelname == null ? null : channelname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_channel.level
     *
     * @return the value of cms_channel.level
     *
     * @mbg.generated
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_channel.level
     *
     * @param level the value for cms_channel.level
     *
     * @mbg.generated
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_channel.parentId
     *
     * @return the value of cms_channel.parentId
     *
     * @mbg.generated
     */
    public Integer getParentid() {
        return parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_channel.parentId
     *
     * @param parentid the value for cms_channel.parentId
     *
     * @mbg.generated
     */
    public void setParentid(Integer parentid) {
        this.parentid = parentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_channel.orderNum
     *
     * @return the value of cms_channel.orderNum
     *
     * @mbg.generated
     */
    public Integer getOrdernum() {
        return ordernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_channel.orderNum
     *
     * @param ordernum the value for cms_channel.orderNum
     *
     * @mbg.generated
     */
    public void setOrdernum(Integer ordernum) {
        this.ordernum = ordernum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_channel.icon
     *
     * @return the value of cms_channel.icon
     *
     * @mbg.generated
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_channel.icon
     *
     * @param icon the value for cms_channel.icon
     *
     * @mbg.generated
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_channel.isDel
     *
     * @return the value of cms_channel.isDel
     *
     * @mbg.generated
     */
    public String getIsdel() {
        return isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_channel.isDel
     *
     * @param isdel the value for cms_channel.isDel
     *
     * @mbg.generated
     */
    public void setIsdel(String isdel) {
        this.isdel = isdel == null ? null : isdel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_channel.createTime
     *
     * @return the value of cms_channel.createTime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_channel.createTime
     *
     * @param createtime the value for cms_channel.createTime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_channel.updateTime
     *
     * @return the value of cms_channel.updateTime
     *
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_channel.updateTime
     *
     * @param updatetime the value for cms_channel.updateTime
     *
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_channel
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", channelname=").append(channelname);
        sb.append(", level=").append(level);
        sb.append(", parentid=").append(parentid);
        sb.append(", ordernum=").append(ordernum);
        sb.append(", icon=").append(icon);
        sb.append(", isdel=").append(isdel);
        sb.append(", createtime=").append(createtime);
        sb.append(", updatetime=").append(updatetime);
        sb.append("]");
        return sb.toString();
    }
}