package com.data.pojo;

import java.io.Serializable;

public class CmsRoleResourceRelKey implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_role_resource_rel.role_id
     *
     * @mbg.generated
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cms_role_resource_rel.resources_id
     *
     * @mbg.generated
     */
    private Integer resourcesId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cms_role_resource_rel
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_role_resource_rel.role_id
     *
     * @return the value of cms_role_resource_rel.role_id
     *
     * @mbg.generated
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_role_resource_rel.role_id
     *
     * @param roleId the value for cms_role_resource_rel.role_id
     *
     * @mbg.generated
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cms_role_resource_rel.resources_id
     *
     * @return the value of cms_role_resource_rel.resources_id
     *
     * @mbg.generated
     */
    public Integer getResourcesId() {
        return resourcesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cms_role_resource_rel.resources_id
     *
     * @param resourcesId the value for cms_role_resource_rel.resources_id
     *
     * @mbg.generated
     */
    public void setResourcesId(Integer resourcesId) {
        this.resourcesId = resourcesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cms_role_resource_rel
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", roleId=").append(roleId);
        sb.append(", resourcesId=").append(resourcesId);
        sb.append("]");
        return sb.toString();
    }
}